Support for creating ipxe.iso on non-x86
ipxe/ipxe pull request #986
Opened 2023-07-03 03:49 UTC by yetist

syslinux only supports the x86 platform, other platforms do not. 
On non-x86 platforms, only UEFI is supported, and steps related to syslinux need to be skipped.

Test passed on loong64.

2023-07-03 12:11 UTC, mcb30 requested changes
The problem with this change is that we want to be able to run `isohybrid` so that we can create a single output file that is usable as either an ISO or a hard disk image, even for non-x86 targets such as ARM or LoongArch64.  This is needed because there are some systems that will fail to recognise an ISO filesystem on a device that isn't a real optical drive (e.g. an ISO image on a USB key, which is quite a common scenario).

This requirement to run `isohybrid` in turn requires that we provide something that looks like `isolinux.bin`, since `isohybrid` is not capable of generating an EFI-only image.  (Hence the comments within `genfsimg`: "Note that the BIOS boot files are required even for an EFI-only ISO, since isohybrid will refuse to work without them".)

At least on Fedora, `isolinux.bin` is provided as part of the `syslinux-nonlinux` package, which is `noarch` since it contains binaries that are executed by the firmware (rather than executed within the installed OS).

I see two viable options:
1. Fix up your distro's syslinux package so that it can build at least the noarch portions on LoongArch64, or
2. Find an alternative to `isohybrid` that does not require `isolinux.bin`.

2023-07-03 13:50 UTC, yetist commented
> 2. Find an alternative to `isohybrid` that does not require `isolinux.bin`.

`grub-mkrescue` provides an example of using `mtools` and `xorriso` to make an iso containing an ESP partition for use on a USB stick.

```
$ grub-mkrescue -v -o /tmp/x.iso
$ fdisk -l /tmp/x.iso
```

2023-07-05 01:22 UTC, yetist commented on src/util/genfsimg
> +    if [[ "${DESTFILE}" =~ ^(BOOTIA32.EFI|BOOTX64.EFI)$ ]]; then
I added `-a` option to genfsimg script to specify arch. 
CI passed.

2023-07-05 11:37 UTC, mcb30 commented on src/util/genfsimg
> +    if [[ "${DESTFILE}" =~ ^(BOOTIA32.EFI|BOOTX64.EFI)$ ]]; then
`genfsimg` can be used to create multi-architecture images (e.g. to create a single image supporting x86_64 UEFI, AArch64 UEFI, LoongArch64 UEFI and x86 BIOS), so an option to specify architecture does not make conceptual sense, unfortunately.

2023-07-10 10:32 UTC, yetist commented on src/util/genfsimg
> +    if [[ "${DESTFILE}" =~ ^(BOOTIA32.EFI|BOOTX64.EFI)$ ]]; then
If the host is x86, everything is fine.
But if the host is arm, arm64 or loongarch64, then at least the `syslinux` command will not execute successfully.

Maybe this patch is not good enough, but the issue exists.

2023-07-10 12:54 UTC, mcb30 commented
@yetist Could you try #992 to see if this solves your issue?

2023-07-10 14:34 UTC, yetist commented
> @yetist Could you try #992 to see if this solves your issue?

Thanks, I think the PR should be closed now.

2023-07-10 14:34 UTC, closed without merging